name: GH Pages Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install mdbook
        run: 'mkdir bin
          && curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.31/mdbook-v0.4.31-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          && mv bin/mdbook ./
          && rm -r bin'

      - name: Install mdbook-pagetoc
        run: 'mkdir bin
          && curl -sSL https://github.com/slowsage/mdbook-pagetoc/releases/download/v0.1.7/mdbook-pagetoc-v0.1.7-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          && mv bin/mdbook-pagetoc ./
          && rm -r bin'

      - name: Restore cached deps
        uses: actions/cache/restore@v3
        with:
          path: '~/.cargo'
          key: ${{ runner.os }}-cargo

      - name: Build preprocessor
        run: 'cargo install --git https://github.com/FarLandsMC/mdbook-fl.git --root .
          && mv bin/mdbook-fl ./
          && rm -r bin'

      - name: Restore cached deps
        uses: actions/cache/restore@v3
        with:
          path: '~/.cargo'
          key: ${{ runner.os }}-cargo

      - name: Build
        run: 'PATH="$PATH:./" mdbook build'

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: book
